/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TeamMemberService } from "../teamMember.service";
import { TeamMemberCreateInput } from "./TeamMemberCreateInput";
import { TeamMember } from "./TeamMember";
import { TeamMemberFindManyArgs } from "./TeamMemberFindManyArgs";
import { TeamMemberWhereUniqueInput } from "./TeamMemberWhereUniqueInput";
import { TeamMemberUpdateInput } from "./TeamMemberUpdateInput";

export class TeamMemberControllerBase {
  constructor(protected readonly service: TeamMemberService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TeamMember })
  async createTeamMember(
    @common.Body() data: TeamMemberCreateInput
  ): Promise<TeamMember> {
    return await this.service.createTeamMember({
      data: data,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        photoUrl: true,
        role: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [TeamMember] })
  @ApiNestedQuery(TeamMemberFindManyArgs)
  async teamMembers(@common.Req() request: Request): Promise<TeamMember[]> {
    const args = plainToClass(TeamMemberFindManyArgs, request.query);
    return this.service.teamMembers({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        photoUrl: true,
        role: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TeamMember })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async teamMember(
    @common.Param() params: TeamMemberWhereUniqueInput
  ): Promise<TeamMember | null> {
    const result = await this.service.teamMember({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        photoUrl: true,
        role: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TeamMember })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateTeamMember(
    @common.Param() params: TeamMemberWhereUniqueInput,
    @common.Body() data: TeamMemberUpdateInput
  ): Promise<TeamMember | null> {
    try {
      return await this.service.updateTeamMember({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          id: true,
          name: true,
          photoUrl: true,
          role: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TeamMember })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteTeamMember(
    @common.Param() params: TeamMemberWhereUniqueInput
  ): Promise<TeamMember | null> {
    try {
      return await this.service.deleteTeamMember({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          name: true,
          photoUrl: true,
          role: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
